// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnmaehdkdgoulohxyozc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubWFlaGRrZGdvdWxvaHh5b3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTk1MDUsImV4cCI6MjA2NTk3NTUwNX0.4lX1VxSP1xWzfvfJUjHp_9yNOsiEqFeoXzV-5JNpq8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);